apiVersion: v1
kind: Pod
metadata:
   name: dop-mailoperations
spec:
   containers:
   - name: dop-mailoperations-container02
     image: ceptravi/dop_mailoperations:latest
     ports:
     - containerPort: 6379